"""Safe readers for the locked P6--P8 product directories.

This module deliberately reads only named products generated by the existing
phase scripts.  It never accepts a filesystem path from an API caller and
never calculates a replacement result when a product is unavailable.
"""

from __future__ import annotations

import csv
import json
from datetime import datetime
from pathlib import Path
from typing import Any

from fastapi import HTTPException


ROOT = Path(__file__).resolve().parents[3]
CONFIG_ROOT = ROOT / "config"
DATA_ROOT = ROOT / "data"
P6_ROOT = DATA_ROOT / "coupling"
P7_ROOT = DATA_ROOT / "inundation"
P8_ROOT = DATA_ROOT / "routing"


def unavailable(product: str) -> HTTPException:
    return HTTPException(
        status_code=503,
        detail={"error": "product_unavailable", "message": f"Validated {product} output is not available."},
    )


def invalid(kind: str, value: str) -> HTTPException:
    return HTTPException(
        status_code=404,
        detail={"error": f"invalid_{kind}", "message": f"The requested {kind} is not available in validated outputs."},
    )


def read_json(path: Path, product: str) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise unavailable(product) from exc
    except (OSError, json.JSONDecodeError) as exc:
        raise HTTPException(status_code=503, detail={"error": "invalid_product", "message": f"Validated {product} output cannot be read."}) from exc
    if not isinstance(payload, dict):
        raise HTTPException(status_code=503, detail={"error": "invalid_product", "message": f"Validated {product} output has an invalid schema."})
    return payload


def read_csv(path: Path, product: str) -> list[dict[str, str]]:
    try:
        with path.open(newline="", encoding="utf-8") as handle:
            return list(csv.DictReader(handle))
    except FileNotFoundError as exc:
        raise unavailable(product) from exc
    except (OSError, csv.Error) as exc:
        raise HTTPException(status_code=503, detail={"error": "invalid_product", "message": f"Validated {product} output cannot be read."}) from exc


def study_area() -> dict[str, Any]:
    return read_json(CONFIG_ROOT / "study_area.json", "study-area configuration")


def p7_summary() -> dict[str, Any]:
    return read_json(P7_ROOT / "metrics" / "p7_summary.json", "P7 summary")


def p7_timeseries() -> list[dict[str, str]]:
    return read_csv(P7_ROOT / "metrics" / "inundation_timeseries.csv", "P7 inundation time series")


def p7_road_impacts() -> list[dict[str, str]]:
    return read_csv(P7_ROOT / "roads" / "road_impact_timeseries.csv", "P7 road-impact time series")


def p7_timestamps() -> list[str]:
    summary = p7_summary()
    timestamps = summary.get("timestamps")
    if not isinstance(timestamps, list) or not all(isinstance(item, str) for item in timestamps):
        raise HTTPException(status_code=503, detail={"error": "invalid_product", "message": "Validated P7 summary has no usable timestamps."})
    return timestamps


def require_timestamp(timestamp: str) -> str:
    try:
        datetime.fromisoformat(timestamp.replace("Z", "+00:00"))
    except ValueError as exc:
        raise HTTPException(status_code=422, detail={"error": "invalid_timestamp", "message": "Timestamp must be ISO-8601 with a timezone."}) from exc
    if timestamp not in p7_timestamps():
        raise invalid("timestamp", timestamp)
    return timestamp


def p7_extent(timestamp: str | None) -> dict[str, Any]:
    summary = p7_summary()
    if timestamp is None:
        path = P7_ROOT / "vectors" / "max_extent.geojson"
        return read_json(path, "P7 maximum flood extent")
    require_timestamp(timestamp)
    timestamps = p7_timestamps()
    index = timestamps.index(timestamp)
    # P7's generator writes extent_NNNN.geojson in precisely timestamp order.
    return read_json(P7_ROOT / "vectors" / f"extent_{index:04d}.geojson", "P7 timestamped flood extent")


def rainfall_sources() -> list[dict[str, Any]]:
    catalog = read_json(DATA_ROOT / "rainfall" / "metadata" / "source_catalog.json", "rainfall source catalog")
    sources = catalog.get("sources")
    if not isinstance(sources, dict):
        raise HTTPException(status_code=503, detail={"error": "invalid_product", "message": "Rainfall source catalog has an invalid schema."})
    result = []
    for source_id, item in sources.items():
        if not isinstance(item, dict):
            continue
        # Catalog metadata only: never trigger a live-source request here.
        result.append({"source_id": source_id, **item})
    return result


def _run_record(phase: str, product: str, payload: dict[str, Any], timestamps: list[str]) -> dict[str, Any]:
    record: dict[str, Any] = {"phase": phase, "product": product, "timestamps": timestamps}
    generated = payload.get("generated_at_utc")
    if isinstance(generated, str):
        record["generated_at_utc"] = generated
    return record


def discover_runs() -> list[dict[str, Any]]:
    """Discover only products whose actual metadata files exist."""
    runs: list[dict[str, Any]] = []
    p6_summary_path = P6_ROOT / "results" / "coupling_summary.json"
    if p6_summary_path.exists():
        payload = read_json(p6_summary_path, "P6 summary")
        timestamps = payload.get("timestamps", [])
        runs.append(_run_record("P6", "coupled surface outputs", payload, timestamps if isinstance(timestamps, list) else []))
    p7_summary_path = P7_ROOT / "metrics" / "p7_summary.json"
    if p7_summary_path.exists():
        payload = p7_summary()
        timestamps = payload.get("timestamps", [])
        runs.append(_run_record("P7", "flood inundation and road impact", payload, timestamps if isinstance(timestamps, list) else []))
    for metadata_path in sorted((P8_ROOT / "metadata").glob("*_provenance.json")) if (P8_ROOT / "metadata").exists() else []:
        payload = read_json(metadata_path, "P8 route provenance")
        timestamp = payload.get("timestamp")
        runs.append(_run_record("P8", "flood-safe route", payload, [timestamp] if isinstance(timestamp, str) else []))
    return runs


def routing_available() -> bool:
    """Whether all immutable P8 inputs required to answer a route exist."""
    config_path = CONFIG_ROOT / "routing.json"
    if not config_path.exists():
        return False
    try:
        config = read_json(config_path, "P8 routing configuration")
        required = (
            config.get("source_road_graph"),
            config.get("source_p7_road_timeseries"),
            config.get("source_p7_road_summary"),
        )
        return all(isinstance(item, str) and (ROOT / item).is_file() for item in required)
    except HTTPException:
        return False
